name: Beecat
favicon: null
layout_spectrum: 0.96844
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#FBCE00'
    - '#CECFCF'
    - '#BC9A00'
  brandStrength: 0.8398945
  lightness: 0.2841232
  saturation: 0.5246457
  rhythmicContrast: 0.02426876
purpose: []
